version: '3'

services:
  db:
    image: postgres
    restart: on-failure:5
    environment:
      POSTGRES_PASSWORD: pgexamplepassword
    volumes:
      - pgexample_db_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: on-failure:5
    ports:
      - 8080:8080

volumes:
  pgexample_db_data: